### ISSUE TITLE
Feature Request: Allow initial Login with .htaccess 

### ISSUE THREAD

**Issue by SomeStrangeName** [MER-C/wiki-java#123]
Looks like the current Wiki class does not allow to open an API connection if the mediawiki installation is additionally protected with an .htaccess file.

Would be nice if you could add that functionality.

**Comment by SomeStrangeName** [comment]
Ok, a simple solution would be to extend the calls this way:

```
package org.wikipedia;

import java.io.IOException;
import java.net.URL;
import java.net.URLConnection;

public class MyWiki extends Wiki {
    public MyWiki(String url, String api) {
	super(url,api);
    }

    @Override
    protected URLConnection makeConnection(String url) throws IOException
    {
	URL url1 = new URL(url);
	URLConnection con = url1.openConnection();
	con.setRequestProperty("Authorization", "Basic "+new sun.misc.BASE64Encoder().encode ("user:password".getBytes()));
	return con;
    }
}
```

Of course User and passwort should not be hard coded.

**Comment by MER-C** [comment]
That is the intended solution. Since this is a rare use case, I don't see the need to add support for it.

**Comment by MER-C** [comment]
That is the intended solution. Since this is a rare use case, I don't see the need to add support for it.
