### ISSUE TITLE
 java.util.zip.ZipException in file Wiki.java: fetch() line 7273

### ISSUE THREAD

**Issue by m-art-in** [MER-C/wiki-java#145]
I only have a litte test program with Wiki.java but already my connection to the Wiki fails. `login(user,password)` throws an uncatched java.util.zip.ZipException in function fetch() line 7273
How should I handel this?

**Comment by MER-C** [comment]
Try setUsingCompressedRequests(false)

**Comment by MER-C** [comment]
No response => closing.

**Comment by m-art-in** [comment]
Could not really be tested yet because of: https://github.com/MER-C/wiki-java/issues/124
