### ISSUE TITLE
Add InputStream support for the upload method 

### ISSUE THREAD

**Issue by kevinmichaelchen** [MER-C/wiki-java#150]
Currently, `upload` only supports File and URL parameters. It'd be nice to support InputStream so you can e.g., stream bytes from a database into MediaWiki.

**Comment by MER-C** [comment]
Sorry for the late reply. I've been thinking about this... what about dumping the stream contents to a temporary file and passing that? I'm very hesitant to add new overloads.

**Comment by MER-C** [comment]
Closing, no response.
