### ISSUE TITLE
Make urlMaxLength configurable (and make wiki-java friendly to custom Mediawiki sites).

### ISSUE THREAD

**Issue by Nirvanchik** [MER-C/wiki-java#168]
URL_LENGTH_LIMIT is hardcoded with 8192 and I have to modify Wiki.java code to make it possible use wiki-java for my special installation of Mediawiki. That installation is on hosting where max url limit is 2048. 
So I would like to have something like this:

    private int urlMaxLength = 8192;
    public void setUrlMaxLength(int maxLength) {
        urlMaxLength = maxLength;
    }

**Comment by MER-C** [comment]
I'm thinking of storing minor configuration variables like this via the Properties or Preferences mechanism. Do you have any preference as to which I should use?

**Comment by MER-C** [comment]
Looking at the problem further, are there any requests where this is still an issue? Lists of titles now get sent via HTTP POST.

**Comment by MER-C** [comment]
Closing. Reopen if this is a problem in HEAD.

**Comment by Nirvanchik** [comment]
Sorry. Created this issue by mistake having older code in mind.
