### ISSUE TITLE
Annoying retries due to unrelated maxlag on WMFWiki derived classes

### ISSUE THREAD

**Issue by PeterBowman** [MER-C/wiki-java#173]
My client library derives from [`WMFWiki`](https://github.com/MER-C/wiki-java/blob/64feb0f1097f5192e5a6f5a41457586112c2a0a4/src/org/wikipedia/WMFWiki.java) (for convenience; I really find the `requiresExtension` method useful). That class stores two static instances of itself in order to handle connections to Meta-Wiki and Wikidata databases ([ref](https://github.com/MER-C/wiki-java/blob/64feb0f1097f5192e5a6f5a41457586112c2a0a4/src/org/wikipedia/WMFWiki.java#L40-L50)) for use in certain class methods, see e.g. [`WMFWiki::getSiteMatrix`](https://github.com/MER-C/wiki-java/blob/64feb0f1097f5192e5a6f5a41457586112c2a0a4/src/org/wikipedia/WMFWiki.java#L146). My client doesn't need them at all since I only need to query stuff from a Wiktionary project. However, last week I was nearly unable to use it since initialization of my class triggered a login request on Wikidata which couldn't complete due to maxlag errors. That is, after a few minutes and several "Current database lag X s exceeds maxlag of Y s, waiting Z s." warnings ([ref](https://github.com/MER-C/wiki-java/blob/master/src/org/wikipedia/Wiki.java#L8357)), my client finally managed to do its intended work.

I'd suggest that `METAWIKI` and `WIKIDATA` static members could be left uninitialized (hence not `final`) until first use, i.e. move the assignment and configuration instructions from the static initialization block into some private method. Then, check against `null` value and call this method from within `getSiteMatrix` and similar.

However, commit https://github.com/MER-C/wiki-java/commit/64feb0f1097f5192e5a6f5a41457586112c2a0a4#diff-ceb7ba312ee4fdc1b0685e93bb0aa46e dropped encapsulation and made those members public, therefore existing client code might break. Perhaps setting a high maxlag value on `METAWIKI` and `WIKIDATA` could be a better fit?

**Comment by MER-C** [comment]
I made that hack for precisely the same reason. However, there are other reasons why one may want to access these objects, for instance to login. There is a better way to do this, which I will commit shortly.

**Comment by MER-C** [comment]
I ended up disabling Wikidata maxlag after a huge lag spike stopped everything. I'm going to leave this open until the WMF adequately resources the Wikidata query service. 

See https://phabricator.wikimedia.org/T243701

**Comment by PeterBowman** [comment]
Thanks!

> There is a better way to do this, which I will commit shortly.

> I ended up disabling Wikidata maxlag after a huge lag spike stopped everything.

For reference: https://github.com/MER-C/wiki-java/commit/75644b98013ec510bf9d8208e1ada1c0517f1075 + https://github.com/MER-C/wiki-java/commit/59708d276e85618fe23d980ae6be12ff1f1728c5.

**Comment by PeterBowman** [comment]
WMF devs are releasing a new Streaming Updated thing which aims to avoid throttling: [ref](https://www.wikidata.org/w/index.php?title=Wikidata:Project_chat&oldid=1382594283#New_WDQS_Streaming_Updater_now_available_on_pre-production_test_server_for_feedback).

**Comment by MER-C** [comment]
The solution for this after 99e7aa571 is to use WMFWikiFarm.

**Comment by MER-C** [comment]
Unclosing, I still need to deal with the instance in WMFWiki.getWikidataItems.
