### ISSUE TITLE
java.lang.NumberFormatException error in getCurrentDatabaseLag()

### ISSUE THREAD

**Issue by michal-josef-spacek** [MER-C/wiki-java#176]
Hi, 

There is issue in method getCurrentDatabaseLag() with bad converting lag to Integer.
Example:
/w/api.php?action=query&format=json&meta=siteinfo&siprop=dbrepllag
Response:
`
{
    "batchcomplete": "",
    "query": {
        "dbrepllag": [
            {
                "host": "db1112",
                "lag": 0.471904993057251
            }
        ]
    }
}
`

lag is 0.471904993057251 and Integer.parseInt(lag) will fail on this.

Fix is something like: 
String s = "0.01";
int i = Double.valueOf(s).intValue();

**Comment by MER-C** [comment]
Fixed in 4e9d3b0d.

**Comment by michal-josef-spacek** [comment]
Thank you, very much :-)
