### ISSUE TITLE
API errors are not caught by callers as intended

### ISSUE THREAD

**Issue by PeterBowman** [MER-C/wiki-java#183]
(Actually a known issue, but reporting here for visibility: [see FIXME](https://github.com/MER-C/wiki-java/blob/6f66b8f441cd99248905528fae07d29446e96787/src/org/wikipedia/Wiki.java#L8431).)

A `Wiki.edit` call can be surrounded by `try-catch` blocks to act upon common error conditions, as documented in [the wiki](https://github.com/MER-C/wiki-java/wiki/Extended-documentation#tips-and-tricks). Immediately after performing the API call, the response is checked in the `edit` method's body against edit conflicts (specific to this action) and a broader set of API errors (via [`checkErrorsAndUpdateStatus`](https://github.com/MER-C/wiki-java/blob/6f66b8f441cd99248905528fae07d29446e96787/src/org/wikipedia/Wiki.java#L8395-L8453)):

https://github.com/MER-C/wiki-java/blob/6f66b8f441cd99248905528fae07d29446e96787/src/org/wikipedia/Wiki.java#L2247-L2253

However, neither of these error handlers is actually used. If we inspect `makeApiCall` closely, we find another handler which predates anything else:

https://github.com/MER-C/wiki-java/blob/6f66b8f441cd99248905528fae07d29446e96787/src/org/wikipedia/Wiki.java#L8281-L8303

The default clause causes callers to propagate an `UnknownError` despite being prepared to respond in a more granular fashion. For instance, edit conflicts are **not** reported as a `ConcurrentModificationException` because of this.

**Comment by MER-C** [comment]
Does e0cc550 fix this issue?

**Comment by PeterBowman** [comment]
That should do it, thank you! I'll merge this into my fork and upload to the production server in a few days, after JDK17 is released.
