### ISSUE TITLE
Add support for specifying articlePath and normalize URLs upon initialization

### ISSUE THREAD

**Issue by aaronjyoder** [MER-C/wiki-java#194]
I run a wiki [here](https://eldenring.soulsborne.wiki/w/Special:Version) that uses `/w/` as the articlePath. I notice that it is hardcoded to `/wiki/` in the code. It was super easy for me to quickly edit `Wiki.java` to add support for specifying the `articlePath`, but this should be built-in or otherwise fetched from the API if possible, because `/w/` is an incredibly common article path, used by the likes of the [RuneScape Wikis](https://runescape.wiki/) and [Minecraft Wiki](https://minecraft.wiki/).

In addition, specifying a script path of `/` (as it appears on `Special:Version`) results in malformed URLs. It feels unnatural to me to specify a blank string for a root script path, and so URI normalization should probably be used instead, meaning you can either supply an empty string or use `/`, whichever feels more natural. Normalizing the variables in `initVars` fixes this, either via Java's `java.net.URI` normalization method (and subsequent call to `toString()`) or via regex, though I think normalizing the URI is a better solution and is what I have done. However, normalizing the URI in this way results in needing to handle a `URISyntaxException`.

I'd be curious to hear thoughts on enhancing the code in these two ways.

Pull request: #195

**Comment by MER-C** [comment]
Fixed in #195.
