### ISSUE TITLE
normalize namespace prefix inside getPageInfo()

### ISSUE THREAD

**Issue by PeterBowman** [MER-C/wiki-java#68]
Test code:
```java
Wiki wiki = new Wiki("pl.wikipedia.org");
Map map = wiki.getPageInfo("Help:Spis treści");
```
This will return ```null``` because the requested full page name ("Help:Spis treści") won't be equal to the server-side normalized title ("Pomoc:Spis treści", [API result](https://pl.wikipedia.org/w/api.php?format=xml&action=query&prop=info&intoken=edit|watch&inprop=protection|displaytitle|watchers&titles=Help%3ASpis+tre%C5%9Bci), *parsedtitle* at [#1318](../blob/79c29d8b4e20e0d8249e7cb32a4d31dbe4ed88e2/src/org/wikipedia/Wiki.java#L1318)) and the condition at line [#1344](../blob/79c29d8b4e20e0d8249e7cb32a4d31dbe4ed88e2/src/org/wikipedia/Wiki.java#L1344) will never be met.

**Comment by MER-C** [comment]
Fixed in  f0c7926 .
