### ISSUE TITLE
for-loop bug in constructTitleString()

### ISSUE THREAD

**Issue by PeterBowman** [MER-C/wiki-java#69]
Test code:
```java
Wiki wiki = new Wiki("en.wiktionary.org");
String[] pages = wiki.getCategoryMembers("Category:Istriot lemmas", 0); // pages.length = 392
Map[] maps = wiki.getPageInfo(pages); // maps.length = 392, but this is now a sparse array
```
```maps``` would store information for no more than 100 pages. The reason is that ```constructTitleString()``` returns an array of only two non-null elements (but length = 8 for this particular case) because of the condition at line [#6968](../blob/79c29d8b4e20e0d8249e7cb32a4d31dbe4ed88e2/src/org/wikipedia/Wiki.java#L6968):
```java
i == titles.length - 1 || i == slowmax - 1
```
This should be as follows:
```java
i == titles.length - 1 || i % (slowmax - 1) == 0
```
Information for the first batch of 50 titles will be correctly retrieved, but the next, bigger one (392 - 50) would be capped to 50 due to API limit restrictions.

**Comment by MER-C** [comment]
Fixed in 704678b. FYI:

```java
i == titles.length - 1 || i % (slowmax - 1) == 0
```

That won't work either, because it eliminates `titles[0]`.
