### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by WolfgangFahl** [MER-C/wiki-java#82]
Today 24 of 28 unit tests fail with:

java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.wikipedia.Wiki.fetch(Wiki.java:6768)
	at org.wikipedia.Wiki.populateNamespaceCache(Wiki.java:1473)
	at org.wikipedia.Wiki.namespaceIdentifier(Wiki.java:1441)
	at org.wikipedia.WikiUnitTest.namespaceIdentifier(WikiUnitTest.java:52)

these are the relevant source code lines:
```java
  // get the text
        String temp;
        try (BufferedReader in = new BufferedReader(new InputStreamReader(
            zipped ? new GZIPInputStream(connection.getInputStream()) : connection.getInputStream(), "UTF-8")))
        {
            String line;
            StringBuilder text = new StringBuilder(100000);
            while ((line = in.readLine()) != null)
            {
                text.append(line);
                text.append("\n");
            }
            temp = text.toString();
        }
```

**Comment by vonloxley** [comment]
Works fine for me 262d74d:
Tests run: 29, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.204 sec - in org.wikipedia.WikiUnitTest

**Comment by MarcoFalke** [comment]
There were some issues with the servers tonight which may be the cause for the EOFException

**Comment by MER-C** [comment]
Works for me. Just another WMF server hiccup.

FYI: the Codeship banner on the readme indicates whether the unit tests are passing.

**Comment by WolfgangFahl** [comment]
The problem persists. I'd like to debug the reason. How can I do this?

**Comment by MER-C** [comment]
1) Trap the URLs fetched and open them in a browser.
2) Use a standard IDE step-through debugger.

**Comment by WolfgangFahl** [comment]
1) http://en.wikipedia.org/w/api.php?format=xml&action=query&meta=siteinfo&siprop=namespaces%7Cnamespacealiases
2) see bug report. 

Thats exactly what I initially did when reporting the bug. Now I am stuck since the URL works in a Browser. I am not using the latest version of the software but it's only a few weeks old.

**Comment by WolfgangFahl** [comment]
When running the tests in the context of mediawiki-japi all tests are o.k. except the one that is called from mediawiki-japi and tests multiple implementations via an interface. The issue is again a java.io.EOFException or if i switch off zipping with
  ```java 
   // zip doesn't work as of 2015-01-20
    wiki.setUsingCompressedRequests(false);
```
the result is simply empty e.g. for http://en.wikipedia.org/w/index.php?maxlag=5&title=Main+Page&action=raw.

with test.wikipedia.org it works ...

**Comment by MER-C** [comment]
Are you using non-secure urls? en.wikipedia is forced HTTPS for everyone as of yesterday.

**Comment by WolfgangFahl** [comment]
@MER-C  - ok thank you. It would be great if you'd reopen the bug as a change request based on this discussion - if using the wrong protocol a proper error message would be very helpful instead of the EOF exception.

**Comment by MER-C** [comment]
It appears Java does not follow the redirect for some reason when it should (https://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html#setInstanceFollowRedirects-boolean-). 

The exception occurs because the response is empty. I consider this a feature, not a bug. A redirect is not the only circumstance resulting in an empty response and all are fatal errors.
