### ISSUE TITLE
Can not download SVG files

### ISSUE THREAD

**Issue by MarcoFalke** [MER-C/wiki-java#84]
Steps to reproduce

    System.out.println(commons.getImage("File:Test2-giron.svg").length);

gives ```2169``` (bytes), though it should be 15594 bytes, actually.

**Comment by MarcoFalke** [comment]
I should note that firefox can not display the SVG and in a text editor it looks "scrambled". Nonetheless, inkscape can open it without any issues, so it may be "just" compressed?

**Comment by MER-C** [comment]
Yeah, it's gzipped.

**Comment by MER-C** [comment]
Fixed in 74fad44.
