### ISSUE TITLE
cant't connect to wiki with api.php in webroot

### ISSUE THREAD

**Issue by Clevero** [MER-C/wiki-java#96]
can't connect with my instance to the english minecrat wiki on http://minecraft.gamepedia.com. i think the main problem is, that the wiki i try connecting to has its api.php not in a subfolder named "w". so a api call with http://minecraft.gamepedia.com/w/api.php returns an error.

the right api.php is in the webroot see here http://minecraft.gamepedia.com/api.php

can anyone please fix this issue?

**Comment by MarcoFalke** [comment]
Please provide some sort of error message or code to reproduce this issue.

I don't see why 

```java
Wiki minecraft = new Wiki("minecraft.gamepedia.com", "");
```
 would not work.

**Comment by MER-C** [comment]
Indeed: did you set the scriptpath to be the empty string?

**Comment by Clevero** [comment]
nope, mistake on my side. sorry for that.

don't saw that the class Wiki has an another constructor for those situations.
old code was 
```Wiki wiki = new Wiki("minecraft.gamepedia.com");```

but with your help the code that works for me is 
```Wiki wiki = new Wiki("minecraft.gamepedia.com", "");```

thanks for your responses :)
